### ISSUE TITLE
Two Vipers on the system

### ISSUE THREAD

**Issue by gjf** [Magisk-Modules-Repo/ViPER4AndroidFX#4]
After update to latest version I have two modules installed (with "no infromation" for the later one):
Looks like not all traces were removed.

![Screenshot_2019-04-01-13-11-50-048_com topjohnwu magisk](https://user-images.githubusercontent.com/322186/55320821-c4741600-5480-11e9-865b-d0bb49fca6b1.png)

**Comment by gjf** [comment]
With the update dated April 2nd it was impossible to update the module - installer says it is already installed and simply uninstalls it.
Anyway after that update/uninstall I still see "ViPER4AndroidFX?" module - and it cannot be uninstalled from Magisk.
The only solution was to boot into recovery and to uninstall"ViPER4AndroidFX?" manually using /data/media/mm.
I think the issue was inproper naming with "?" at the end of the name that does not allow to uninstall the module normally and "removing remnants" did not proceed it because of naming.
Right after that fake "ViPER4AndroidFX?" disappeared in the list and I was able to install the module again normally.

**Comment by Zackptg5** [comment]
Without logs I can't help you. Magisk has had issues migrating modules on some devices when upgrading from 18 to 19. V4A uninstall now does the same thing as ticking the trash icon in magisk manager when booted (so you'll need to reboot to remove it). If you flash it in twrp, it'll actually remove it.
Regardless, just delete the v4a folder in magisk mod directory and flash the new one after that
